### ISSUE TITLE
Support CASEMAPPING, add a helper function to casefold

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#260]
Example code: https://github.com/jesopo/ircstates/blob/ca9abfc34b78b12e34bacd5515b5cae64d690dd5/ircstates/casemap.py#L9

We use `toLowerCase` now, but that's not correct as that will also apply to unicode characters, not just ascii.

Something like `IrcClient.casefold(string)` would probably work here. It would look at `options.CASEMAPPING` to determine how to fold.

@prawnsalad thoughts? Neither kiwi or lounge currently handle it.

**Comment by prawnsalad** [comment]
Makes sense to add this. Wouldn't it have an upper and lower function rather than a single casefold function though?

**Comment by xPaw** [comment]
I guess so. I haven't seen upper case being relevant anywhere though.

What would custom casefolding apply to? Nicks and channel names? Should it also be done on command names and whatnot?

**Comment by prawnsalad** [comment]
Spoke to the inspircd dev on this:
~~~
[13:20:03]  prawnsalad:	so if we use it to just compare channel names and nicks, then thats prtty much all it would be used for in the client side?
[13:21:27]  SadieP:	yeah
~~~

So I guess a fast (since it would be a very hot function getting called all the time in clients) simple string compare function would work I guess? `IrcClient.caseCompare(str1, str2)`?

**Comment by xPaw** [comment]
I think a separate function to lowercase would be good to have too. I think TL has a couple of places where it's beneficial.

**Comment by xPaw** [comment]
Prototyped here: https://github.com/kiwiirc/irc-framework/compare/casefolding

**Comment by xPaw** [comment]
The functions should be good to go. Can you verify the use of these functions across the code base and write up some docs for it?
